# Generated by Django 5.1.4 on 2025-01-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('comision', models.DecimalField(decimal_places=2, help_text='Porcentaje de comisión', max_digits=5)),
            ],
        ),
    ]
