# Generated by Django 5.1.4 on 2025-01-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='comision',
            field=models.DecimalField(decimal_places=3, help_text='Porcentaje de comisión', max_digits=5),
        ),
    ]
