# Generated by Django 5.1.4 on 2025-01-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comerciales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comercial',
            name='id',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
